"""Add Taro session tracking fields to user

Revision ID: 94216a734e91
Revises: 20260215_taro_session_card_draw
Create Date: 2026-02-16 09:52:22.995281+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94216a734e91'
down_revision: Union[str, None] = '20260215_taro_session_card_draw'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plugin_config_plugin_name', table_name='plugin_config')
    op.drop_table('plugin_config')
    op.drop_index('ix_addon_tarif_plans_plan', table_name='addon_tarif_plans')
    op.alter_column('arcana', 'arcana_type',
               existing_type=postgresql.ENUM('MAJOR_ARCANA', 'CUPS', 'WANDS', 'SWORDS', 'PENTACLES', name='arcanatype'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'MAJOR_ARCANA'::arcanatype"))
    op.drop_constraint('uq_arcana_number_suit_rank', 'arcana', type_='unique')
    op.drop_index('ix_country_position', table_name='country')
    op.drop_constraint('feature_usage_user_id_fkey', 'feature_usage', type_='foreignkey')
    op.create_foreign_key(None, 'feature_usage', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_password_reset_token_token', 'password_reset_token', type_='unique')
    op.drop_constraint('uq_permission_name', 'permission', type_='unique')
    op.alter_column('role', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_role_name', 'role', type_='unique')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_permission_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permission', ['permission_id'], ['id'])
    op.drop_index('ix_subscription_stripe_subscription_id', table_name='subscription')
    op.drop_constraint('uq_subscription_stripe_subscription_id', 'subscription', type_='unique')
    op.create_index(op.f('ix_subscription_provider_subscription_id'), 'subscription', ['provider_subscription_id'], unique=True)
    op.alter_column('taro_card_draw', 'position',
               existing_type=postgresql.ENUM('PAST', 'PRESENT', 'FUTURE', name='cardposition'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('taro_card_draw', 'orientation',
               existing_type=postgresql.ENUM('UPRIGHT', 'REVERSED', name='cardorientation'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('uq_taro_card_draw_session_position', 'taro_card_draw', type_='unique')
    op.drop_constraint('taro_card_draw_arcana_id_fkey', 'taro_card_draw', type_='foreignkey')
    op.drop_constraint('taro_card_draw_session_id_fkey', 'taro_card_draw', type_='foreignkey')
    op.alter_column('taro_session', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'EXPIRED', 'CLOSED', name='tarosessionstatus'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::tarosessionstatus"))
    op.alter_column('token_bundle', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # Add Taro session tracking columns with defaults for existing rows
    op.add_column('user', sa.Column('daily_taro_sessions_used', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user', sa.Column('daily_taro_limit', sa.Integer(), nullable=True, server_default='3'))
    # Update existing rows to have default values
    op.execute('UPDATE "user" SET daily_taro_sessions_used = 0 WHERE daily_taro_sessions_used IS NULL')
    op.execute('UPDATE "user" SET daily_taro_limit = 3 WHERE daily_taro_limit IS NULL')
    # Make columns non-nullable
    op.alter_column('user', 'daily_taro_sessions_used', existing_type=sa.Integer(), nullable=False)
    op.alter_column('user', 'daily_taro_limit', existing_type=sa.Integer(), nullable=False)
    op.drop_index('ix_user_stripe_customer_id', table_name='user')
    op.drop_constraint('uq_user_stripe_customer_id', 'user', type_='unique')
    op.create_index(op.f('ix_user_payment_customer_id'), 'user', ['payment_customer_id'], unique=True)
    op.drop_index('ix_user_invoice_stripe_invoice_id', table_name='user_invoice')
    op.drop_constraint('uq_user_invoice_stripe_invoice_id', 'user_invoice', type_='unique')
    op.create_index(op.f('ix_user_invoice_provider_session_id'), 'user_invoice', ['provider_session_id'], unique=True)
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user_roles', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_user_token_balance_user_id', 'user_token_balance', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_token_balance_user_id', 'user_token_balance', ['user_id'])
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.drop_index(op.f('ix_user_invoice_provider_session_id'), table_name='user_invoice')
    op.create_unique_constraint('uq_user_invoice_stripe_invoice_id', 'user_invoice', ['provider_session_id'])
    op.create_index('ix_user_invoice_stripe_invoice_id', 'user_invoice', ['provider_session_id'], unique=False)
    op.drop_index(op.f('ix_user_payment_customer_id'), table_name='user')
    op.create_unique_constraint('uq_user_stripe_customer_id', 'user', ['payment_customer_id'])
    op.create_index('ix_user_stripe_customer_id', 'user', ['payment_customer_id'], unique=False)
    op.drop_column('user', 'daily_taro_limit')
    op.drop_column('user', 'daily_taro_sessions_used')
    op.alter_column('token_bundle', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('taro_session', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTIVE', 'EXPIRED', 'CLOSED', name='tarosessionstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::tarosessionstatus"))
    op.create_foreign_key('taro_card_draw_session_id_fkey', 'taro_card_draw', 'taro_session', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('taro_card_draw_arcana_id_fkey', 'taro_card_draw', 'arcana', ['arcana_id'], ['id'])
    op.create_unique_constraint('uq_taro_card_draw_session_position', 'taro_card_draw', ['session_id', 'position'])
    op.alter_column('taro_card_draw', 'orientation',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('UPRIGHT', 'REVERSED', name='cardorientation'),
               existing_nullable=False)
    op.alter_column('taro_card_draw', 'position',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PAST', 'PRESENT', 'FUTURE', name='cardposition'),
               existing_nullable=False)
    op.drop_index(op.f('ix_subscription_provider_subscription_id'), table_name='subscription')
    op.create_unique_constraint('uq_subscription_stripe_subscription_id', 'subscription', ['provider_subscription_id'])
    op.create_index('ix_subscription_stripe_subscription_id', 'subscription', ['provider_subscription_id'], unique=False)
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_unique_constraint('uq_role_name', 'role', ['name'])
    op.alter_column('role', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('uq_permission_name', 'permission', ['name'])
    op.create_unique_constraint('uq_password_reset_token_token', 'password_reset_token', ['token'])
    op.drop_constraint(None, 'feature_usage', type_='foreignkey')
    op.create_foreign_key('feature_usage_user_id_fkey', 'feature_usage', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_country_position', 'country', ['position'], unique=False)
    op.create_unique_constraint('uq_arcana_number_suit_rank', 'arcana', ['number', 'suit', 'rank'])
    op.alter_column('arcana', 'arcana_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MAJOR_ARCANA', 'CUPS', 'WANDS', 'SWORDS', 'PENTACLES', name='arcanatype'),
               existing_nullable=False,
               existing_server_default=sa.text("'MAJOR_ARCANA'::arcanatype"))
    op.create_index('ix_addon_tarif_plans_plan', 'addon_tarif_plans', ['tarif_plan_id'], unique=False)
    op.create_table('plugin_config',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('plugin_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'disabled'::character varying"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('enabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('disabled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='plugin_config_pkey')
    )
    op.create_index('ix_plugin_config_plugin_name', 'plugin_config', ['plugin_name'], unique=False)
    # ### end Alembic commands ###
