"""Events for Taro plugin - event-driven architecture."""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class TaroSessionRequestedEvent:
    """Event emitted when user requests a new Taro session."""

    user_id: str
    requested_at: datetime
    daily_limit: int = 3
    max_follow_ups: int = 3

    def __post_init__(self):
        """Validate event data."""
        if not self.user_id:
            raise ValueError("user_id is required")


@dataclass
class TaroSessionCreatedEvent:
    """Event emitted after Taro session is successfully created."""

    session_id: str
    user_id: str
    spread_id: str
    expires_at: datetime
    created_at: datetime
    card_arcana_ids: List[str]  # IDs of the 3 cards in spread
    initial_tokens_consumed: int = 10

    def __post_init__(self):
        """Validate event data."""
        if not self.session_id or not self.user_id:
            raise ValueError("session_id and user_id are required")
        if len(self.card_arcana_ids) != 3:
            raise ValueError("Must have exactly 3 cards in spread")


@dataclass
class TaroFollowUpRequestedEvent:
    """Event emitted when user asks a follow-up question."""

    session_id: str
    user_id: str
    question: str
    follow_up_type: str  # SAME_CARDS, ADDITIONAL, NEW_SPREAD
    requested_at: datetime

    def __post_init__(self):
        """Validate event data."""
        valid_types = {"SAME_CARDS", "ADDITIONAL", "NEW_SPREAD"}
        if self.follow_up_type not in valid_types:
            raise ValueError(f"follow_up_type must be one of {valid_types}")


@dataclass
class TaroFollowUpGeneratedEvent:
    """Event emitted after follow-up interpretation is generated."""

    session_id: str
    user_id: str
    follow_up_count: int
    tokens_consumed: int
    interpretation: str
    new_cards: Optional[List[str]] = None  # IDs of new cards if ADDITIONAL/NEW_SPREAD
    created_at: Optional[datetime] = None

    def __post_init__(self):
        """Set defaults if needed."""
        if not self.created_at:
            self.created_at = datetime.utcnow()


@dataclass
class TaroSessionExpiredEvent:
    """Event emitted when session expires (30 minutes pass)."""

    session_id: str
    user_id: str
    expired_at: datetime
    follow_ups_count: int
    total_tokens_consumed: int

    def __post_init__(self):
        """Validate event data."""
        if not self.session_id or not self.user_id:
            raise ValueError("session_id and user_id are required")


@dataclass
class TaroSessionClosedEvent:
    """Event emitted when user explicitly closes session."""

    session_id: str
    user_id: str
    closed_at: datetime
    follow_ups_count: int
    total_tokens_consumed: int

    def __post_init__(self):
        """Validate event data."""
        if not self.session_id or not self.user_id:
            raise ValueError("session_id and user_id are required")


@dataclass
class TaroInterpretationGeneratedEvent:
    """Event emitted after card interpretations are generated by LLM."""

    card_ids: List[str]  # IDs of cards interpreted
    session_id: str
    tokens_used: int
    created_at: datetime

    def __post_init__(self):
        """Validate event data."""
        if not self.card_ids:
            raise ValueError("At least one card must be interpreted")
